const products = [
  {
    //Apps Category
    name: "Photo Editing Pro",
    description:
      "Enhance and transform your photos with our powerful editing app. Edit colors, apply filters, add effects, and more. Perfect for both amateur and professional photographers.",
    count: 50,
    price: 35,
    category: "Apps",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Compatibility", value: "Android" },
      { key: "Size", value: "Under 50MB" },
    ],
  },
  {
    name: "Fitness Tracker Pro",
    description:
      "Achieve your fitness goals with our comprehensive tracker app. Monitor your steps, calories burned, heart rate, sleep patterns, and more. Get personalized insights and stay motivated on your fitness journey.",
    count: 25,
    price: 25,
    category: "Apps",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Compatibility", value: "IOS" },
      { key: "Size", value: "Under 50MB" },
    ],
  },
  {
    name: "Language Learning Master",
    description:
      "Learn a new language easily with our interactive language learning app. Practice vocabulary, grammar, and pronunciation through fun exercises, quizzes, and interactive lessons. Start speaking fluently in no time.",
    count: 100,
    price: 15,
    category: "Apps",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Compatibility", value: "IOS" },
      { key: "Size", value: "50MB-100MB" },
    ],
  },
  {
    name: "Recipe Genius",
    description:
      "Discover and cook delicious meals with our recipe app. Browse through a vast collection of recipes, save your favorites, create shopping lists, and get step-by-step instructions. Elevate your culinary skills.",
    count: 75,
    price: 5,
    category: "Apps",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Compatibility", value: "Android" },
      { key: "Size", value: "50MB-100MB" },
    ],
  },
  {
    name: "Meditation Oasis",
    description:
      "Find inner peace and reduce stress with our meditation and mindfulness app. Access a wide range of guided meditation sessions, relaxation techniques, breathing exercises, and soothing sounds. Restore balance and tranquility in your life.",
    count: 40,
    price: 10,
    category: "Apps",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Compatibility", value: "Android" },
      { key: "Size", value: "50MB-100MB" },
    ],
  },
  {
    name: "Travel Planner Plus",
    description:
      "Plan your dream vacation effortlessly with our comprehensive travel planner app. Discover popular destinations, book flights and accommodations, create itineraries, and explore local attractions. Make every trip memorable.",
    count: 60,
    price: 8,
    category: "Apps",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Compatibility", value: "IOS" },
      { key: "Size", value: "Over 100MB" },
    ],
  },
  {
    name: "Budget Tracker Deluxe",
    description:
      "Take control of your finances with our user-friendly budgeting app. Track your income, expenses, and savings goals. Set budgets, receive spending alerts, and visualize your financial progress. Achieve financial freedom.",
    count: 30,
    price: 12,
    category: "Apps",
    images: [],
    rating: 2,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Compatibility", value: "Android" },
      { key: "Size", value: "Over 100MB" },
    ],
  },
  {
    name: "Fitness Coach Pro",
    description:
      "Get personalized fitness training and guidance with our virtual coach app. Access workout routines, video demonstrations, nutrition tips, and progress tracking. Stay motivated and achieve your fitness goals.",
    count: 25,
    price: 28,
    category: "Apps",
    images: [],
    rating: 1,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Compatibility", value: "IOS" },
      { key: "Size", value: "Under 50MB" },
    ],
  },
  //Accessories Category
  {
    name: "Mechanical Gaming Keyboard",
    description:
      "Enhance your gaming experience with our mechanical gaming keyboard. It offers precise and responsive key switches, customizable RGB lighting, and programmable macros for a competitive edge.",
    count: 100,
    price: 80,
    category: "Accessories",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Class", value: "Keyboard" },
      { key: "Connection", value: "Wired" },
      { key: "Compatibility", value: "Windows" },
      { key: "Gaming", value: "Yes" },
    ],
  },
  {
    name: "Wireless Bluetooth Keyboard",
    description:
      "Stay productive on the go with our wireless Bluetooth keyboard. Its compact design and wireless connectivity make it ideal for tablets and smartphones. Enjoy comfortable typing wherever you are.",
    count: 100,
    price: 40,
    category: "Accessories",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Class", value: "Keyboard" },
      { key: "Connection", value: "Wireless" },
      { key: "Compatibility", value: "macOS" },
      { key: "Gaming", value: "No" },
    ],
  },
  {
    name: "Ergonomic Gaming Mouse",
    description:
      "Dominate your gaming sessions with our ergonomic gaming mouse. Its precision sensors, adjustable DPI, and programmable buttons give you the ultimate control and accuracy.",
    count: 50,
    price: 60,
    category: "Accessories",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Class", value: "Mouse" },
      { key: "Connection", value: "Wired" },
      { key: "Compatibility", value: "Windows" },
      { key: "Gaming", value: "Yes" },
    ],
  },
  {
    name: "Backlit Gaming Keyboard",
    description:
      " Immerse yourself in gaming with our backlit keyboard and mouse combo. The keyboard features customizable lighting effects.",
    count: 40,
    price: 90,
    category: "Accessories",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Class", value: "Keyboard" },
      { key: "Connection", value: "Wired" },
      { key: "Compatibility", value: "Windows" },
      { key: "Gaming", value: "Yes" },
    ],
  },
  {
    name: "Wireless Mechanical Keyboard",
    description:
      "Experience the best of both worlds with our wireless mechanical keyboard. Enjoy the tactile feedback and durability of mechanical key switches without the hassle of cables. Perfect for gamers and typists.",
    count: 60,
    price: 130,
    category: "Accessories",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Class", value: "Keyboard" },
      { key: "Connection", value: "Wireless" },
      { key: "Compatibility", value: "macOS" },
      { key: "Gaming", value: "No" },
    ],
  },
  {
    name: "Silent Wireless Mouse",
    description:
      "Work or study in peace with our silent wireless mouse. It provides a quiet and smooth clicking experience, minimizing distractions for you and those around you.",
    count: 5,
    price: 100,
    category: "Accessories",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Class", value: "Mouse" },
      { key: "Connection", value: "Wired" },
      { key: "Compatibility", value: "Windows" },
      { key: "Gaming", value: "No" },
    ],
  },
  {
    name: "RGB Gaming Keyboard",
    description:
      "Take your gaming setup to the next level with our RGB gaming keyboard. Choose from a wide range of vibrant lighting effects and customize them to match your style and preferences.",
    count: 80,
    price: 60,
    category: "Accessories",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Class", value: "Mouse" },
      { key: "Connection", value: "Wired" },
      { key: "Compatibility", value: "Windows" },
      { key: "Gaming", value: "No" },
    ],
  },
  {
    name: "Compact Mechanical Keyboard",
    description:
      "Maximize your desk space without compromising on typing comfort with our compact mechanical keyboard. Its small form factor and mechanical key switches make it a perfect choice for minimalistic setups.",
    count: 90,
    price: 90,
    category: "Accessories",
    images: [],
    rating: 2,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Class", value: "Keyboard" },
      { key: "Connection", value: "Wired" },
      { key: "Compatibility", value: "macOS" },
      { key: "Gaming", value: "No" },
    ],
  },
  // Beauty
  {
    name: "Hydrating Facial Moisturizer",
    description:
      "Nourish and hydrate your skin with our luxurious facial moisturizer. Formulated with natural ingredients, it deeply moisturizes, leaving your skin soft, smooth, and rejuvenated.",
    count: 200,
    price: 40,
    category: "Beauty",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Type", value: "Skin" }],
  },
  {
    name: "Organic Argan Oil Hair Serum",
    description:
      "Transform your hair with our organic argan oil hair serum. It repairs damaged strands, tames frizz, adds shine, and promotes healthier hair growth. Experience silky, lustrous locks.",
    count: 150,
    price: 20,
    category: "Beauty",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Type", value: "Hair" }],
  },
  {
    name: "Vitamin C Brightening Serum",
    description:
      "Achieve a brighter and more radiant complexion with our vitamin C brightening serum. Packed with antioxidants, it fades dark spots, evens out skin tone, and boosts collagen production.",
    count: 100,
    price: 35,
    category: "Beauty",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Type", value: "Skin" }],
  },
  {
    name: "Natural Mineral Eyeshadow Palette",
    description:
      "Create stunning eye looks with our natural mineral eyeshadow palette. It features a range of versatile and highly pigmented shades that blend effortlessly for both everyday and glamorous looks.",
    count: 120,
    price: 25,
    category: "Beauty",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Type", value: "Skin" }],
  },
  {
    name: "Anti-Aging Night Cream",
    description:
      "Rejuvenate your skin overnight with our anti-aging night cream. Infused with potent ingredients, it helps reduce fine lines, wrinkles, and uneven texture, promoting a youthful and radiant complexion.",
    count: 180,
    price: 50,
    category: "Beauty",
    images: [],
    rating: 2,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Type", value: "Skin" }],
  },
  {
    name: "Exfoliating Body Scrub",
    description:
      "Achieve smooth and glowing skin with our exfoliating body scrub. It gently buffs away dead skin cells, revealing a softer and more radiant complexion. Indulge in the refreshing scent and enjoy a luxurious shower experience.",
    count: 120,
    price: 25,
    category: "Beauty",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Type", value: "Skin" }],
  },
  {
    name: "Waterproof Mascara",
    description:
      "Define and volumize your lashes with our waterproof mascara. Its long-lasting formula ensures smudge-free and flake-free wear, even in humid conditions or during water activities.",
    count: 200,
    price: 15,
    category: "Beauty",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Type", value: "Skin" }],
  },
  // Books
  {
    name: "To Kill a Mockingbird",
    description:
      "Dive into the classic novel To Kill a Mockingbird by Harper Lee. Set in the 1930s, this Pulitzer Prize-winning story explores themes of racial injustice and the loss of innocence through the eyes of young Scout Finch.",
    count: 50,
    price: 13,
    category: "Books",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Genre", value: "Fiction" }],
  },
  {
    name: "Becoming",
    description:
      "Discover the inspiring memoir Becoming by former First Lady Michelle Obama. In this deeply personal book, she shares her journey from childhood on the South Side of Chicago to the White House, offering insights and life lessons along the way.",
    count: 75,
    price: 20,
    category: "Books",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Genre", value: "Memoir" }],
  },
  {
    name: "The Hobbit",
    description:
      "Embark on an epic adventure with The Hobbit by J.R.R. Tolkien. Follow Bilbo Baggins as he joins a company of dwarves on a quest to reclaim their homeland, encountering dragons, elves, and a mysterious ring along the way.",
    count: 30,
    price: 9,
    category: "Books",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Genre", value: "Fantasy" }],
  },
  {
    name: "Educated",
    description:
      "Engage in the captivating memoir Educated by Tara Westover. This remarkable story follows the author's journey from her isolated upbringing in a strict survivalist family to her pursuit of education and self-discovery.",
    count: 40,
    price: 16,
    category: "Books",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Genre", value: "Memoir" }],
  },
  {
    name: "Sapiens: A Brief History of Humankind",
    description:
      "Explore the fascinating exploration of human history in Sapiens: A Brief History of Humankind by Yuval Noah Harari. This thought-provoking book takes readers on a journey from the emergence of Homo sapiens to the present, covering topics such as biology, culture, and the impact of technology.",
    count: 60,
    price: 15,
    category: "Books",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [{ key: "Genre", value: "Non-Fiction" }],
  },
  // Computers/Monitors
  {
    name: "Dell UltraSharp U2419H Monitor",
    description:
      "Immerse yourself in stunning visuals with the Dell UltraSharp U2419H Monitor. Its 24-inch Full HD display delivers vibrant colors, sharp details, and wide viewing angles, making it ideal for work or entertainment.",
    count: 50,
    price: 250,
    category: "Monitors",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "24 Inch" },
      { key: "Refresh Rate", value: "60Hz" },
      { key: "Connectivity", value: "HDMI" },
      { key: "Panel", value: "IPS" },
    ],
  },
  {
    name: "LG 27GN950-B Gaming Monitor",
    description:
      "Level up your gaming experience with the LG 27GN950-B Gaming Monitor. Featuring a 27-inch Nano IPS display with 4K resolution and a fast 144Hz refresh rate, it delivers smooth gameplay and stunning visuals.",
    count: 30,
    price: 900,
    category: "Monitors",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "27 Inch" },
      { key: "Refresh Rate", value: "144Hz" },
      { key: "Connectivity", value: "DisplayPort" },
      { key: "Panel", value: "IPS" },
    ],
  },
  {
    name: "Samsung Odyssey G9 Curved Gaming Monitor",
    description:
      "Immerse yourself in the ultimate gaming experience with the Samsung Odyssey G9 Curved Gaming Monitor. Its massive 49-inch curved QLED display with a 240Hz refresh rate and 1000R curvature brings games to life like never before.",
    count: 20,
    price: 1800,
    category: "Monitors",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "27 Inch" },
      { key: "Refresh Rate", value: "240Hz" },
      { key: "Connectivity", value: "DisplayPort" },
      { key: "Panel", value: "QLED" },
    ],
  },
  {
    name: "ASUS ProArt PA329Q Professional Monitor",
    description:
      "Unleash your creativity with the ASUS ProArt PA329Q Professional Monitor. Designed for graphic designers, photographers, and video editors, its 32-inch 4K UHD display offers accurate color reproduction and precise image quality.",
    count: 40,
    price: 1300,
    category: "Monitors",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "24 Inch" },
      { key: "Refresh Rate", value: "60Hz" },
      { key: "Connectivity", value: "HDMI" },
      { key: "Panel", value: "IPS" },
    ],
  },
  {
    name: "Acer R240HY Full HD Monitor",
    description:
      "Enjoy crisp visuals and a sleek design with the Acer R240HY Full HD Monitor. Its 23.8-inch display with IPS technology delivers vibrant colors and wide viewing angles, making it ideal for multimedia and everyday use.",
    count: 30,
    price: 250,
    category: "Monitors",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "24 Inch" },
      { key: "Refresh Rate", value: "60Hz" },
      { key: "Connectivity", value: "HDMI" },
      { key: "Panel", value: "IPS" },
    ],
  },
  // Computers/Tablets
  {
    name: "Apple iPad Pro (2021)",
    description:
      "Experience the power and versatility of the Apple iPad Pro. With its stunning Liquid Retina XDR display, powerful M1 chip, and support for Apple Pencil and Magic Keyboard, it offers unparalleled performance for work and creativity on the go.",
    count: 50,
    price: 1100,
    category: "Tablets",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "10 Inch" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "iPadOS" },
    ],
  },
  {
    name: "Samsung Galaxy Tab S7+",
    description:
      "Unleash your productivity with the Samsung Galaxy Tab S7+. Its 12.4-inch Super AMOLED display, powerful Snapdragon 865+ processor, and included S Pen make it the perfect companion for work, entertainment, and creative tasks.",
    count: 30,
    price: 850,
    category: "Tablets",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "12 Inch" },
      { key: "Storage", value: "356GB" },
      { key: "OS", value: "Android" },
    ],
  },
  {
    name: "Microsoft Surface Pro 7",
    description:
      "Experience the versatility of the Microsoft Surface Pro 7. With its detachable Type Cover, powerful Intel Core processor, and Windows 10 operating system, it transforms from a tablet to a laptop in seconds, enabling you to work and create anywhere.",
    count: 40,
    price: 1000,
    category: "Tablets",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "12 Inch" },
      { key: "Storage", value: "512GB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "Lenovo Tab P11 Pro",
    description:
      "Enjoy entertainment and productivity in style with the Lenovo Tab P11 Pro. Its 11.5-inch OLED display, Qualcomm Snapdragon 730G processor, and quad-speaker system deliver immersive visuals and audio, making it perfect for multimedia consumption.",
    count: 50,
    price: 500,
    category: "Tablets",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "10 Inch" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "Android" },
    ],
  },
  {
    name: "Amazon Fire HD 10",
    description:
      "Enjoy entertainment, e-books, and Alexa hands-free on the Amazon Fire HD 10 tablet. Its 10.1-inch Full HD display, quad-core processor, and access to Amazon's vast content ecosystem make it an affordable and feature-rich option for casual use.",
    count: 50,
    price: 150,
    category: "Tablets",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "10 Inch" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "Android" },
    ],
  },
  // Printers
  {
    name: "HP OfficeJet Pro 9025 All-in-One Printer",
    description:
      "Boost productivity and streamline your office tasks with the HP OfficeJet Pro 9025 All-in-One Printer. This wireless printer offers fast printing, scanning, copying, and faxing capabilities, along with smart features like automatic double-sided printing and mobile printing options.",
    count: 50,
    price: 300,
    category: "Printers",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  {
    name: "HP OfficeJet Pro 9025 All-in-One Printer",
    description:
      "Boost productivity and streamline your office tasks with the HP OfficeJet Pro 9025 All-in-One Printer. This wireless printer offers fast printing, scanning, copying, and faxing capabilities, along with smart features like automatic double-sided printing and mobile printing options.",
    count: 50,
    price: 300,
    category: "Printers",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  {
    name: "Epson EcoTank ET-4760 Wireless Printer",
    description:
      "Experience hassle-free printing and cost savings with the Epson EcoTank ET-4760 Wireless Printer. Its supersized ink tanks eliminate the need for cartridges, providing high-quality prints with ultra-low printing costs.",
    count: 50,
    price: 500,
    category: "Printers",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  {
    name: "Canon PIXMA PRO-100 Wireless Photo Printer",
    description:
      "Print professional-quality photos with the Canon PIXMA PRO-100 Wireless Photo Printer. Its advanced 8-ink system delivers stunning color accuracy and detail, making it a perfect choice for photographers and creative professionals.",
    count: 50,
    price: 500,
    category: "Printers",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  {
    name: "Brother HL-L2390DW Monochrome Laser Printer",
    description:
      "Print professional-looking documents with the Brother HL-L2390DW Monochrome Laser Printer. Its compact design and wireless connectivity make it suitable for home offices and small businesses, offering fast printing and automatic double-sided printing.",
    count: 50,
    price: 300,
    category: "Printers",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  {
    name: "Xerox VersaLink C405/DN Color Laser Printer",
    description:
      "Experience vibrant color prints and efficient workflow with the Xerox VersaLink C405/DN Color Laser Printer. Its easy-to-use touchscreen interface, high-quality output, and advanced security features make it suitable for small to medium-sized businesses.",
    count: 50,
    price: 750,
    category: "Printers",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  // Cameras
  {
    name: "Canon EOS 5D Mark IV DSLR Camera",
    description:
      "Capture stunning images and videos with the Canon EOS 5D Mark IV DSLR Camera. It features a 30.4-megapixel full-frame sensor, 4K video recording, and advanced autofocus capabilities, making it a top choice for professional photographers and videographers.",
    count: 50,
    price: 2500,
    category: "Cameras",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  {
    name: "Sony Alpha a7 III Mirrorless Camera",
    description:
      "Experience exceptional image quality and performance with the Sony Alpha a7 III Mirrorless Camera. It boasts a 24.2-megapixel full-frame sensor, 4K video recording, and 5-axis image stabilization, making it ideal for both photography and videography enthusiasts.",
    count: 50,
    price: 2000,
    category: "Cameras",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  {
    name: "Nikon D850 DSLR Camera",
    description:
      "Unleash your creativity with the Nikon D850 DSLR Camera. It combines a 45.7-megapixel full-frame sensor, fast continuous shooting, and exceptional low-light performance, making it a versatile tool for professional photographers and enthusiasts alike.",
    count: 50,
    price: 2900,
    category: "Cameras",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  {
    name: "Fujifilm X-T4 Mirrorless Camera",
    description:
      "Embrace the world of mirrorless photography with the Fujifilm X-T4. This compact and powerful camera features a 26.1-megapixel APS-C sensor, 4K video recording, and in-body image stabilization, making it perfect for both photography and videography enthusiasts.",
    count: 50,
    price: 1700,
    category: "Cameras",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  {
    name: "Panasonic Lumix GH5 Mirrorless Camera",
    description:
      "Unleash your creativity and capture stunning videos with the Panasonic Lumix GH5 Mirrorless Camera. It features a 20.3-megapixel Micro Four Thirds sensor, 4K video recording at 60 fps, and 5-axis Dual I.S. 2 image stabilization for smooth and steady footage.",
    count: 50,
    price: 1800,
    category: "Cameras",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [],
  },
  // Computers/Laptops/Lenovo
  {
    name: "Lenovo ThinkPad X1 Carbon (8th Gen)",
    description:
      "The Lenovo ThinkPad X1 Carbon (8th Gen) is a premium ultrabook designed for professionals. With its lightweight and durable carbon fiber construction, powerful performance, and impressive battery life, it is perfect for productivity on the go.",
    count: 50,
    price: 1600,
    category: "Computers/Laptops/Lenovo",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "14 Inch" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "512GB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "Lenovo Yoga C940",
    description:
      "The Lenovo Yoga C940 is a versatile 2-in-1 laptop that combines performance, portability, and a stunning display. Its flexible design allows you to use it as a laptop, tablet, or in tent mode, while the powerful internals ensure smooth multitasking and entertainment.",
    count: 50,
    price: 1300,
    category: "Computers/Laptops/Lenovo",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "14 Inch" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "1TB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "Lenovo Legion 5 Gaming Laptop",
    description:
      "The Lenovo Legion 5 is a powerful gaming laptop built for immersive gaming experiences. It combines a high-refresh-rate display, powerful graphics, and advanced cooling technology to deliver smooth gameplay and responsive performance.",
    count: 30,
    price: 1300,
    category: "Computers/Laptops/Lenovo",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "15.6 Inch" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "512GB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "Lenovo IdeaPad Flex 5",
    description:
      "The Lenovo IdeaPad Flex 5 is a budget-friendly 2-in-1 laptop that offers versatility and performance. Its flexible hinge allows you to switch between laptop and tablet modes, while the AMD Ryzen processor and solid-state drive ensure smooth multitasking and fast boot times.",
    count: 60,
    price: 700,
    category: "Computers/Laptops/Lenovo",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "14 Inch" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "512GB" },
      { key: "OS", value: "Windows" },
    ],
  },
  // Computers/Laptops/Dell
  {
    name: "Dell XPS 13 (2021)",
    description:
      "The Dell XPS 13 (2021) is a premium ultrabook known for its slim design, stunning display, and powerful performance. With its InfinityEdge display, Intel processors, and long battery life, it is perfect for both work and entertainment.",
    count: 60,
    price: 1300,
    category: "Computers/Laptops/Dell",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "14 Inch" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "512GB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "Dell Inspiron 15 7000",
    description:
      "The Dell Inspiron 15 7000 is a versatile laptop that offers a balance of performance and affordability. It features a 15.6-inch display, powerful processors, and a dedicated graphics card, making it suitable for both work and casual gaming.",
    count: 60,
    price: 1000,
    category: "Computers/Laptops/Dell",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "15.6 Inch" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "1TB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "Dell Precision 5550 Mobile Workstation",
    description:
      "The Dell Precision 5550 is a high-performance mobile workstation designed for professionals who require powerful computing capabilities on the go. It features a 15.6-inch display, professional-grade graphics, and extensive connectivity options for demanding workloads.",
    count: 60,
    price: 2900,
    category: "Computers/Laptops/Dell",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "15.6 Inch" },
      { key: "RAM", value: "32GB" },
      { key: "Storage", value: "1TB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "Dell G7 15 Gaming Laptop",
    description:
      "The Dell G7 15 is a gaming laptop designed for gamers who require high-performance hardware for an immersive gaming experience. It features a 15.6-inch display with high refresh rate, powerful processors, and dedicated graphics, making it ideal for gaming enthusiasts.",
    count: 60,
    price: 1300,
    category: "Computers/Laptops/Dell",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "15.6 Inch" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "512GB" },
      { key: "OS", value: "Windows" },
    ],
  },
  // Computers/Laptops/HP
  {
    name: "HP Spectre x360",
    description:
      "The HP Spectre x360 is a premium 2-in-1 laptop that combines sleek design, powerful performance, and versatile functionality. With its convertible form factor, vibrant display, and long battery life, it is perfect for both work and entertainment.",
    count: 60,
    price: 1500,
    category: "Computers/Laptops/HP",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "14 Inch" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "512GB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "HP Envy 15",
    description:
      "The HP Envy 15 is a powerful and stylish laptop designed for creators and multimedia enthusiasts. It features a high-resolution display, powerful processors, and dedicated graphics, making it ideal for photo editing, video rendering, and immersive entertainment.",
    count: 60,
    price: 1300,
    category: "Computers/Laptops/HP",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "15.6 Inch" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "1TB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "HP Pavilion 14",
    description:
      "The HP Pavilion 14 is a budget-friendly laptop that offers reliable performance and essential features for everyday computing. It features a compact design, crisp display, and a range of connectivity options, making it suitable for students and casual users.",
    count: 60,
    price: 700,
    category: "Computers/Laptops/HP",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "14 Inch" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "512GB" },
      { key: "OS", value: "Windows" },
    ],
  },
  {
    name: "HP Omen 17",
    description:
      "The HP Omen 17 is a gaming laptop built for immersive gaming experiences. It features a large display with high refresh rate, powerful processors, and dedicated graphics, making it ideal for gamers who demand high-performance hardware.",
    count: 60,
    price: 1800,
    category: "Computers/Laptops/HP",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "Display", value: "15.6 Inch" },
      { key: "RAM", value: "16GB" },
      { key: "Storage", value: "1TB" },
      { key: "OS", value: "Windows" },
    ],
  },
  //Smartphones/Apple
  {
    name: "iPhone 12 Pro",
    description:
      "The iPhone 12 Pro is Apple's flagship smartphone that combines cutting-edge technology, advanced photography capabilities, and powerful performance. With its stunning Super Retina XDR display, A14 Bionic chip, and pro-grade camera system, it delivers an exceptional user experience.",
    count: 60,
    price: 1000,
    category: "Smartphones/Apple",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "6GB" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "IOS" },
    ],
  },
  {
    name: "iPhone SE (2020)",
    description:
      "The iPhone SE (2020) is a compact and affordable smartphone that offers powerful performance and a familiar design. With its A13 Bionic chip, advanced camera system, and Retina HD display, it provides a great user experience at a budget-friendly price.",
    count: 60,
    price: 400,
    category: "Smartphones/Apple",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "4GB" },
      { key: "Storage", value: "64GB" },
      { key: "OS", value: "IOS" },
    ],
  },
  {
    name: "iPhone 11",
    description:
      "The iPhone 11 is a feature-rich smartphone that offers impressive performance, a vibrant display, and advanced camera capabilities. With its A13 Bionic chip, dual-camera system, and all-day battery life, it provides a premium user experience.",
    count: 60,
    price: 700,
    category: "Smartphones/Apple",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "4GB" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "IOS" },
    ],
  },
  {
    name: "iPhone XR",
    description:
      "The iPhone XR is a stylish and capable smartphone that offers a large display, powerful performance, and advanced camera features. With its A12 Bionic chip, Liquid Retina display, and TrueDepth camera system, it delivers an immersive user experience.",
    count: 60,
    price: 600,
    category: "Smartphones/Apple",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "4GB" },
      { key: "Storage", value: "64GB" },
      { key: "OS", value: "IOS" },
    ],
  },
  {
    name: "iPhone XS",
    description:
      "The iPhone XS is a premium smartphone known for its sleek design, powerful performance, and impressive camera capabilities. With its Super Retina OLED display, A12 Bionic chip, and dual-camera system, it delivers an exceptional user experience.",
    count: 20,
    price: 900,
    category: "Smartphones/Apple",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "4GB" },
      { key: "Storage", value: "256GB" },
      { key: "OS", value: "IOS" },
    ],
  },
  // Smartphones/Samsung
  {
    name: "Samsung Galaxy S21 Ultra",
    description:
      "The Samsung Galaxy S21 Ultra is a premium smartphone that offers a stunning display, powerful performance, and advanced camera capabilities. With its Dynamic AMOLED 2X display, Exynos 2100/Qualcomm Snapdragon 888 processor, and versatile quad-camera system, it provides an exceptional user experience.",
    count: 20,
    price: 1200,
    category: "Smartphones/Samsung",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "Android" },
    ],
  },
  {
    name: "Samsung Galaxy Note 20 Ultra",
    description:
      "The Samsung Galaxy Note 20 Ultra is a productivity-focused smartphone that combines a large display, powerful performance, and enhanced S Pen functionality. With its Dynamic AMOLED 2X display, Exynos 990/Qualcomm Snapdragon 865+ processor, and versatile triple-camera system, it offers a premium user experience.",
    count: 20,
    price: 1300,
    category: "Smartphones/Samsung",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "256GB" },
      { key: "OS", value: "Android" },
    ],
  },
  {
    name: "Samsung Galaxy S20 FE",
    description:
      "The Samsung Galaxy S20 FE (Fan Edition) is a feature-packed smartphone that offers flagship-level performance at a more affordable price. With its Super AMOLED display, Exynos 990/Qualcomm Snapdragon 865 processor, and versatile triple-camera system, it delivers a premium user experience.",
    count: 20,
    price: 700,
    category: "Smartphones/Samsung",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "6GB" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "Android" },
    ],
  },
  {
    name: "Samsung Galaxy A52",
    description:
      "The Samsung Galaxy A52 is a mid-range smartphone that offers a blend of performance, style, and affordability. With its Super AMOLED display, Qualcomm Snapdragon 720G processor, and versatile quad-camera system, it provides a reliable user experience for everyday use.",
    count: 20,
    price: 400,
    category: "Smartphones/Samsung",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "4GB" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "Android" },
    ],
  },
  // Smartphones/OnePlus
  {
    name: "OnePlus 9 Pro",
    description:
      "The OnePlus 9 Pro is a flagship smartphone that offers a premium design, high-end performance, and advanced camera capabilities. With its Fluid AMOLED display, Qualcomm Snapdragon 888 processor, and Hasselblad collaboration for the camera system, it provides an exceptional user experience.",
    count: 20,
    price: 1000,
    category: "Smartphones/OnePlus",
    images: [],
    rating: 5,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "Android" },
    ],
  },
  {
    name: "OnePlus 9",
    description:
      "The OnePlus 9 is a powerful smartphone that combines top-of-the-line features and performance at a competitive price point. With its Fluid AMOLED display, Qualcomm Snapdragon 888 processor, and Hasselblad collaboration for the camera system, it offers a premium user experience.",
    count: 20,
    price: 800,
    category: "Smartphones/OnePlus",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "Android" },
    ],
  },
  {
    name: "OnePlus Nord 2",
    description:
      "The OnePlus Nord 2 is a mid-range smartphone that offers a balance of performance, design, and affordability. With its Fluid AMOLED display, MediaTek Dimensity 1200 processor, and versatile camera system, it delivers a great user experience at a budget-friendly price.",
    count: 20,
    price: 400,
    category: "Smartphones/OnePlus",
    images: [],
    rating: 3,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "6GB" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "Android" },
    ],
  },
  {
    name: "OnePlus 8T",
    description:
      "The OnePlus 8T is a high-performance smartphone that offers a smooth and responsive user experience. With its Fluid AMOLED display, Qualcomm Snapdragon 865 processor, and versatile camera system, it provides flagship-level features at a competitive price.",
    count: 20,
    price: 700,
    category: "Smartphones/OnePlus",
    images: [],
    rating: 4,
    reviewsNumber: 0,
    reviews: [],
    attrs: [
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "OS", value: "Android" },
    ],
  },
];

module.exports = products;
